# Generated by Django 3.1.1 on 2022-03-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elections_name', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(verbose_name='date de la publication')),
            ],
        ),
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('login', models.CharField(max_length=50)),
                ('mdp', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('date_naissance', models.DateTimeField(verbose_name='date de naissance')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.elections')),
                ('personnes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.personnes')),
            ],
        ),
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('personnes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.personnes')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('votes', models.ImageField(default=0, upload_to='')),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.elections')),
            ],
        ),
    ]
